## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx

julia:
  - 1.0
  - nightly

notifications:
  email: false
git:
  depth: 99999999

matrix:
  allow_failures:
  - julia: nightly

before_install:
  - sudo apt-get -y install hdf5-tools

addons:
  homebrew:
    packages:
    - hdf5

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("BrkgaMpIpr")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("BrkgaMpIpr")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

