## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx

julia:
  - 1.2
  - nightly

codecov: true

notifications:
  email: false

matrix:
  allow_failures:
  - julia: nightly

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi

addons:
  apt:
    packages:
      - hdf5-tools
  homebrew:
    packages:
    - hdf5

after_success:
  - julia -e 'cd(Pkg.dir("BrkgaMpIpr")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("BrkgaMpIpr")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

