## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx

julia:
  - 1.2
  - nightly

codecov: true

notifications:
  email: false

matrix:
  allow_failures:
  - julia: nightly

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi

addons:
  apt:
    packages:
      - hdf5-tools
  homebrew:
    packages:
    - hdf5

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

#script:
  #- julia -e 'import Pkg; Pkg.clone(pwd())'
  #- julia -e 'import Pkg; Pkg.test("PkgName",coverage=true)'

after_success:
  #- julia -e 'using Pkg; Pkg.add("Documenter")'
  #- julia -e 'using Pkg; cd(Pkg.dir("BrkgaMpIpr")); include(joinpath("docs", "make.jl"))'
  - julia -e 'using Pkg; cd(Pkg.dir("BrkgaMpIpr")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'using Pkg; cd(Pkg.dir("BrkgaMpIpr")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'